### ISSUE TITLE
Date format in more precise time: YYYY-MM-DD-hh-mm-ss-z

### ISSUE THREAD

**Issue by Barachia** [JMendes1995/py_heideltime#15]
Hi! I found that the library only supports date formats in YYYY-MM-DD. Is it possible to add hours, minutes, seconds and timezones as well? As a result, for example the expression to '4 hours ago' does not get resolved properly.

**Comment by JMendes1995** [comment]
hi @Barachia
According of this example of py_heildeltime you can also get the time of the event. 
![image](https://user-images.githubusercontent.com/35015528/101290061-fb730100-37f7-11eb-97ed-16e2bc1436f4.png)

I think you wanted something like this I suppose.
` 2020-10-26T12:00:00-UTC+01:00`
however, I have to remind you, this package is running the original Java standalone version of  heideltime [https://github.com/amineabdaoui/python-heideltime](url). 

About the expression  `4 hours ago` you are right, the result don't have a good look as you can see in the following image. even so, this is the result that the heildetime returned.
I am afraid that i cant help with that.
![image](https://user-images.githubusercontent.com/35015528/101290538-e51a7480-37fa-11eb-85b9-9c5a28a850ea.png)

kind regards.
Jorge Mendes

**Comment by Barachia** [comment]
Alright, thanks that clears things up for me!
