### ISSUE TITLE
Heideltime version, how to upgrade/downgrade?

### ISSUE THREAD

**Issue by MorenoLaQuatra** [JMendes1995/py_heideltime#16]
Hi, 

First of all, thank you for the great library and for sharing your work!

I'm opening the issue to ask you what is the version of Heideltime included in this wrapper. I tried to compare its results in for the task of Timeline Summarization. Specifically, I tried to compare the results with the one offered by the version embedded in [tilse](https://github.com/smartschat/tilse/tree/master/tilse/tools/heideltime) and (if I didn't make any major mistake) the results differ by a relevant margin. 

I would like to align those results by trying to align the versions of the Heideltime libraries (at least I can try to determine possible errors from my side). The Heideltime version used here is the standalone one? If some of you has already used **tilse** do you think is possible to use [their file](https://github.com/smartschat/tilse/blob/master/tilse/tools/heideltime/apply-heideltime.jar) in `py_heideltime` ([here](https://github.com/MorenoLaQuatra/py_heideltime/blob/master/py_heideltime/Heideltime/de.unihd.dbs.heideltime.standalone.jar))?

Thank you in advance!

Moreno

**Comment by JMendes1995** [comment]
Hello @MorenoLaQuatra 
First of all thank you for using py_heideltime.
The version used in this solution is heideltime 2.2.1 (https://github.com/HeidelTime/heideltime/releases/tag/VERSION2.2.1)

Kind regards.
Jorge Mendes.

**Comment by MorenoLaQuatra** [comment]
Thank you for the quick answer! Is it the standalone version?

**Comment by JMendes1995** [comment]
Hello

Yes is the standalone version.
Cheers.
Jorge Mendes.

**Comment by MorenoLaQuatra** [comment]
Sorry, I got it just after asking so I deleted the question. Thank you again!
