### ISSUE TITLE
py_heideltime raises error when passed a text with emojis

### ISSUE THREAD

**Issue by hmosousa** [JMendes1995/py_heideltime#21]
# Description
Passing a text that contains an emoji raises the following error:
`Error: module 'emoji' has no attribute 'get_emoji_regexp'`

This is has to do with the deprecation of get_emoji_regexp() in version 2.0.0 [see](https://github.com/carpedm20/emoji/issues/222#issuecomment-1200303280)

# Reproduction
```python
from py_heideltime import py_heideltime

results = py_heideltime("text with emoji 😀")
```

**Comment by rncampos** [comment]
problem solved as follows: https://carpedm20.github.io/emoji/docs/#replacing-and-removing-emoji
