### ISSUE TITLE
Error when running py_heideltime for document "19_RussoJap" from WikiWars corpus.

### ISSUE THREAD

**Issue by hmosousa** [JMendes1995/py_heideltime#23]
Running the `py_heideltime` for document "19_RussoJap" from WikiWars corpus raises the following error:
```shell
error: unbalanced parenthesis at position 47
```
This is caused by the use of regular expressions in the [`refactor_text()`](https://github.com/JMendes1995/py_heideltime/blob/4b74a4c0c90724ed289c46aca8c8e1799ebaa033/py_heideltime/py_heideltime.py#L171) function. which is interpreting the tag contents to be replaces as a regex.

## Reproduce
```python
form py_heideltime.py_heideltime import refactor_text
tag_contents = [' tid="t47" type="TIME" value="1904-02-13)TNI">the night of 13 February']
normalized_dates = ["1904-02-13)TNI"]
tagged_text = 'The Japanese attempted to deny the Russians use of Port Arthur. During <TIMEX3 tid="t47" type="TIME" value="1904-02-13)TNI">the night of 13 February</TIMEX3>.'

result = refactor_text(normalized_dates, tag_contents, tagged_text)
```

## Fix
One solution would be to use `str.replace()` instead of the regular expressions. I tried on my machine and it passed in all the tests in the test folder.

```python
def refactor_text(normalized_dates, tag_contents, tagged_text):
    """Replace the TIMEX3 tags with the normalized dates in the tagged text."""
    for tag_content, date in zip(tag_contents, normalized_dates):
        tagged_text = tagged_text.replace(f"<TIMEX3{tag_content}</TIMEX3>", f"<d>{date}</d>", 1)
    return tagged_text
```

**Comment by JMendes1995** [comment]
Hello @hmosousa

First of all i want to thank you for using the lib py_heideltime.

Indeed there is a bug for that example, thank you for mentioning that.

However, i followed your fix and it seems to be working fine by now.
`root@9e5a43bc3361:/var/log/py_heideltime/tests# python3 main.py
[[('1904-02-13)TNI', '<TIMEX3 tid="t3" type="TIME" value="XXXX-02-13)TNI">the night of 13 February')], 'The Japanese attempted to deny the Russians use of Port Arthur. During <d>1904-02-13)TNI</d></TIMEX3>.', 'The Japanese attempted to deny the Russians use of Port Arthur. During <TIMEX3 tid="t47" type="TIME" value="1904-02-13)TNI"><TIMEX3 tid="t3" type="TIME" value="XXXX-02-13)TNI">the night of 13 February</TIMEX3></TIMEX3>.', {'heideltime_processing': 1.7698278427124023, 'py_heideltime_text_normalization': 6.9141387939453125e-06}]`
https://github.com/JMendes1995/py_heideltime/pull/24/

i recommend you to update py_heideltime version by running 
`pip install git+https://github.com/JMendes1995/py_heideltime.git`

Kind Regards.
Jorge Mendes

**Comment by hmosousa** [comment]
Thank you for the quick response. Will close the issue.
